name: Feature request
description: Suggest an idea for this project
title: "[IDEA]: "
labels: [idea]
body:
  - type: textarea
    attributes:
      label: The Idea
      description: Add your idea, and be as descriptive as possible.
    validations:
      required: true
