name: Publish

on:
  release:
    types: [published]

env:
  DENO_VERSION: vx.x.x

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{env.DENO_VERSION}}

      - name: Publish
        if: github.event_name == 'release'
        run: deno publish
